In [2]:
from google.colab import files

uploaded = files.upload()

Saving train.csv to train.csv

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("train.csv")

In [5]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [6]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales']

In [7]:
df.shape

(9800, 18)

In [8]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [11]:
df = df.drop_duplicates()

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code      float64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
dtype: object

In [14]:
df["Order Date"] = pd.to_datetime(df["Order Date"], dayfirst=True)
df["Ship Date"] = pd.to_datetime(df["Ship Date"], dayfirst=True)

In [15]:
df[["Order Date", "Ship Date"]].head()

  Order Date  Ship Date
0 2017-11-08 2017-11-11
1 2017-11-08 2017-11-11
2 2017-06-12 2017-06-16
3 2016-10-11 2016-10-18
4 2016-10-11 2016-10-18

In [16]:
df["Year"] = df["Order Date"].dt.year

In [17]:
df["Month"] = df["Order Date"].dt.month_name()

In [18]:
df["Quarter"] = df["Order Date"].dt.quarter

In [19]:
df["Day"] = df["Order Date"].dt.day_name()

In [20]:
df["Shipping Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

In [21]:
text_cols = df.select_dtypes(include="object").columns

for col in text_cols:
    df[col] = df[col].str.strip()

In [22]:
df["Customer Name"] = df["Customer Name"].str.title()
df["City"] = df["City"].str.title()
df["State"] = df["State"].str.title()
df["Category"] = df["Category"].str.title()
df["Sub-Category"] = df["Sub-Category"].str.title()

In [23]:
df[df["Sales"] <= 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Year, Month, Quarter, Day, Shipping Days]
Index: []

[0 rows x 23 columns]

In [24]:
print("Total Sales:", df["Sales"].sum())

Total Sales: 2261536.7827000003

In [25]:
print("Total Sales:", df["Sales"].sum())

Total Sales: 2261536.7827000003

In [26]:
print("Average Sales:", df["Sales"].mean())

Average Sales: 230.7690594591837

In [27]:
print("Total Orders:", df["Order ID"].nunique())

Total Orders: 4922

In [28]:
print("Total Customers:", df["Customer ID"].nunique())

Total Customers: 793

In [29]:
sales_by_category = df.groupby("Category")["Sales"].sum().reset_index()

sales_by_category

          Category        Sales
0        Furniture  728658.5757
1  Office Supplies  705422.3340
2       Technology  827455.8730

In [30]:
sales_by_region = df.groupby("Region")["Sales"].sum().reset_index()

sales_by_region

    Region        Sales
0  Central  492646.9132
1     East  669518.7260
2    South  389151.4590
3     West  710219.6845

In [31]:
sales_by_state = df.groupby("State")["Sales"].sum().reset_index()

sales_by_state

                   State        Sales
0                Alabama   19510.6400
1                Arizona   35272.6570
2               Arkansas   11678.1300
3             California  446306.4635
4               Colorado   31841.5980
5            Connecticut   13384.3570
6               Delaware   27322.9990
7   District Of Columbia    2865.0200
8                Florida   88436.5320
9                Georgia   48219.1100
10                 Idaho    4382.4860
11              Illinois   79236.5170
12               Indiana   48718.4000
13                  Iowa    4443.5600
14                Kansas    2914.3100
15              Kentucky   36458.3900
16             Louisiana    9131.0500
17                 Maine    1270.5300
18              Maryland   23705.5230
19         Massachusetts   28634.4340
20              Michigan   76136.0740
21             Minnesota   29863.1500
22           Mississippi   10771.3400
23              Missouri   22205.1500
24               Montana    5589.3520
25              Nebraska    7464.9300
26                Nevada   16729.1020
27         New Hampshire    7292.5240
28            New Jersey   34610.9720
29            New Mexico    4783.5220
30              New York  306361.1470
31        North Carolina   55165.9640
32          North Dakota     919.9100
33                  Ohio   75130.3500
34              Oklahoma   19683.3900
35                Oregon   17284.4620
36          Pennsylvania  116276.6500
37          Rhode Island   22525.0260
38        South Carolina    8481.7100
39          South Dakota    1315.5600
40             Tennessee   30661.8730
41                 Texas  168572.5322
42                  Utah   11220.0560
43               Vermont    8929.3700
44              Virginia   70636.7200
45            Washington  135206.8500
46         West Virginia    1209.8240
47             Wisconsin   31173.4300
48               Wyoming    1603.1360

In [32]:
top_customers = (
    df.groupby("Customer Name")["Sales"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
      .reset_index()
)

top_customers

        Customer Name      Sales
0         Sean Miller  25043.050
1        Tamara Chand  19052.218
2        Raymond Buch  15117.339
3        Tom Ashbrook  14595.620
4       Adrian Barton  14473.571
5        Ken Lonsdale  14175.229
6        Sanjit Chand  14142.334
7        Hunter Lopez  12873.298
8        Sanjit Engle  12209.438
9  Christopher Conant  12129.072

In [33]:
monthly_sales = (
    df.groupby("Month")["Sales"]
      .sum()
      .reset_index()
)

monthly_sales

        Month        Sales
0       April  136283.0006
1      August  157315.9270
2    December  321480.1695
3    February   59371.1154
4     January   94291.6296
5        July  145535.6890
6        June  145837.5233
7       March  197573.5872
8         May  154086.7237
9    November  350161.7110
10    October  199496.2947
11  September  300103.4117

In [34]:
df.to_csv("cleaned_sales_data.csv", index=False)

In [35]:
from google.colab import files
files.download("cleaned_sales_data.csv")